# .github/actions/cache-restore/action.yaml

name: "Build Cache restoration"
description: "Setup a NodeJS environment and restore build cache if any, given a node version"

inputs:
  node-version:
    description: "Node version to use, default to LTS Fermium (14.x)"
    required: true
    default: lts/fermium
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.build-cache.outputs.cache-hit }}

runs:
  using: "composite" # Mandatory parameter
  steps:
    # Setup a Node environment given a node version
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Build
      id: build-cache
      uses: actions/cache@v2
      with:
        path: build
        # Make the cache dependencies depending on the node version for matrix
        # testing: the package-lock.json would be the same so an additional
        # criteria is required to distinguish the caches
        key: build-${{ inputs.node-version }}-${{ hashFiles('**/src/**') }}
