# .github/actions/cache-restore/action.yaml

name: "Cache restoration"
description: "Setup a NodeJS environment and restore node_modules cache, given a node version"

inputs:
  node-version:
    description: "Node version to use, default to LTS Fermium (14.x)"
    required: true
    default: lts/fermium
outputs:
  cache-hit:
    description: "Did restore node_modules from cache?"
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: "composite" # Mandatory parameter
  steps:
    # Setup a Node environment given a node version
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        # Make the cache dependencies depending on the node version for matrix
        # testing: the package-lock.json would be the same so an additional
        # criteria is required to distinguish the caches
        key: node-modules-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
