name: "Node Module Cache"
description: "Caches node_modules between workflow jobs"

outputs:
  cache-hit:
    description: "Whether the cache was hit"
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock', '**/package.json') }}
