name: PR Workflow CI

on: pull_request

jobs:
  cancelprevious:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules

      - name: Download dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Downloading dependencies"
          npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
      - run: npm run lint

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-nm

      - uses: ./.github/actions/build-restore
        id: cache-build

      - name: Create New Build from Source Change
        if: steps.cache-build.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Creating new build"
          npm run build

      - name: Create New Build from Deps Change
        if: steps.cache-nm.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Downloading dependencies"
          npm install

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
      - run: npm run test
