name: Code checking

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14

      - name: Download dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Downloading dependencies"
          npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14
      - run: npm run lint

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - uses: ./.github/actions/build-restore
        id: cache-node-modules
        with:
          node-version: 14

      - name: Create new build
        if: steps.build-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Creating new build"
          npm run build

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14
      - run: npm run test
