# perfect

name: Code checking

on: pull_request

jobs:
  Intall_Deps_Setup_Node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 14, 15]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14

      - name: Download dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Downloading dependencies"
          npm install

  Lint:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14
      - run: npm run lint

  Build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
      - uses: ./.github/actions/build-restore
        id: cache-build
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create new build
        if: steps.cache-build.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Creating new build"
          npm run build

  Test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deps-restore
        id: cache-node-modules
        with:
          node-version: 14
      - run: npm run test
